name: Build Treemble

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install webview2-runtime
          rustup target add x86_64-pc-windows-msvc

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Install cargo-tauri
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: treemble-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*
