name: Build Treemble

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install webview2-runtime
          rustup target add x86_64-pc-windows-msvc

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: echo "No additional setup needed for macOS"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build
